[greeter]
theme-name = Everforest-Green-Dark
icon-theme-name = Papirus-Dark
font-name = JetBrainsMono Nerd Font 12
background = /usr/share/backgrounds/xfce/xfce-x.svg
user-background = false
position = 50%,center 50%,center
clock-format = %A, %B %d   %H:%M
indicators = ~host;~spacer;~clock;~spacer;~session;~power
